name: async_searchable_dropdown
description: This Flutter package helps create a dropdown which it's items are fetched upon search.
version: 0.0.7+4
homepage: https://github.com/bilalraad/async_searchable_dropdown

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  async: ^2.9.0
  collection: ^1.16.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
